name: Build and Release Nginx Mainline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BROTLI_REPO: https://github.com/google/ngx_brotli.git
      QUICHE_REPO: https://github.com/cloudflare/quiche
      NGINX_MAINLINE: 1.25

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libpcre3 libpcre3-dev zlib1g-dev libssl-dev \
          cmake golang curl git unzip perl python3 nasm pkg-config clang jq

        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Get Latest Nginx Version (${{ env.NGINX_MAINLINE }})
      id: get_nginx
      run: |
        version=$(curl -s https://nginx.org/en/download.html \
          | grep -oP "nginx-${NGINX_MAINLINE}\.\d+(?=\.tar\.gz)" \
          | sed "s/nginx-//" | sort -V | tail -1)

        echo "LATEST_VERSION=$version" >> $GITHUB_ENV
        echo "Latest version resolved: $version"

    - name: Build Nginx ${{ env.LATEST_VERSION }}
      run: |
        mkdir -p build && cd build

        git clone --recursive $QUICHE_REPO
        curl -O https://nginx.org/download/nginx-${LATEST_VERSION}.tar.gz
        tar zxvf nginx-${LATEST_VERSION}.tar.gz

        git clone $BROTLI_REPO
        cd ngx_brotli && git submodule update --init && cd ..

        cd nginx-${LATEST_VERSION}

        ./configure \
          --prefix=$PWD/nginx-install \
          --with-http_ssl_module \
          --with-http_v2_module \
          --with-http_v3_module \
          --with-http_realip_module \
          --with-http_stub_status_module \
          --with-http_gzip_static_module \
          --with-cc-opt="-O2 -I../quiche/include" \
          --with-ld-opt="-Wl,--as-needed -Wl,-rpath,$PWD/../quiche/target/release -L../quiche/target/release" \
          --with-openssl=../quiche/deps/boringssl \
          --add-module=../ngx_brotli

        make -j$(nproc)
        make install

        tar -czf nginx-${LATEST_VERSION}.tar.gz -C nginx-install .

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nginx-${{ env.LATEST_VERSION }}
        name: Nginx ${{ env.LATEST_VERSION }}
        body: |
          自动构建 Nginx v${{ env.LATEST_VERSION }}（含 HTTP/3、Brotli 模块）
        files: build/nginx-${{ env.LATEST_VERSION }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
