name: Build and Release Nginx 1.25.4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NGINX_VERSION: 1.25.4
      BROTLI_REPO: https://github.com/google/ngx_brotli.git
      QUICHE_REPO: https://github.com/cloudflare/quiche

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libpcre3 libpcre3-dev zlib1g-dev libssl-dev \
          cmake golang curl git unzip perl python3 nasm pkg-config clang jq

        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Prepare Build Environment
      run: |
        mkdir -p build
        cd build

        # 下载 quiche + 子模块
        git clone https://github.com/cloudflare/quiche
        cd quiche
        git submodule update --init --recursive
        cargo build --release
        cd ..

        # 下载 nginx
        curl -O https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
        tar zxvf nginx-${NGINX_VERSION}.tar.gz

        # 下载 brotli
        git clone https://github.com/google/ngx_brotli
        cd ngx_brotli && git submodule update --init --recursive
        cd ..

    - name: Build Nginx ${{ env.NGINX_VERSION }}
      run: |
        cd build/nginx-${NGINX_VERSION}

        ./configure \
          --prefix=$PWD/nginx-install \
          --with-http_ssl_module \
          --with-http_v2_module \
          --with-http_v3_module \
          --with-http_realip_module \
          --with-http_stub_status_module \
          --with-http_gzip_static_module \
          --with-cc-opt="-O2 -I../quiche/include" \
          --with-ld-opt="-Wl,--as-needed -Wl,-rpath,../quiche/target/release -L../quiche/target/release" \
          --with-openssl=../quiche/deps/boringssl \
          --add-module=../ngx_brotli

        make -j$(nproc)
        make install

        tar -czf nginx-${NGINX_VERSION}.tar.gz -C nginx-install .

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nginx-${{ env.NGINX_VERSION }}
        name: Nginx ${{ env.NGINX_VERSION }}
        body: |
          自动构建 Nginx v${{ env.NGINX_VERSION }}（含 HTTP/3、Brotli 模块）
        files: build/nginx-${{ env.NGINX_VERSION }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
